version: "2"

services:
    db:
        image: mysql:latest
        container_name: catechdojo_db
        ports:
            - 3306:3306
        environment: 
            - MYSQL_ROOT_PASSWORD=password
            
    server:
        build: ./server
        container_name: catechdojo_server
        ports:
            - 8080:8080
        depends_on: 
            - "db"

   
        